'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.3053
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  强类型资源类，用于查找本地化字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("EWF_Protect_System.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  为使用此强类型资源类的所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property bear() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("bear", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 @echo off
        '''setlocal enabledelayedexpansion
        '''for %%i in (C D E F G H I J K L M N O P Q R S T U V W X Y Z) do (fsutil fsinfo drivetype %%i:|find &quot;固定&quot;&gt;nul &amp;&amp; for /f &quot;delims=&quot; %%j in (&quot;%%i&quot;) do set partition=!partition! %%j:)
        '''cd /d &quot;%SystemRoot%\system32&quot;
        '''setlocal enabledelayedexpansion
        '''for %%j in (%partition%) do (fsutil fsinfo drivetype %%j|find &quot;固定&quot;&gt;nul &amp;&amp; Filter %%j|find &quot;ENABLED&quot;&gt;nul &amp;&amp; for /f &quot;delims=&quot; %%k in (&quot;%%j&quot;) do set partition1=!partition1! %%k)
        '''setlocal disabledelayedexpansion
        '''setlocal enable [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property look() As String
            Get
                Return ResourceManager.GetString("look", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property X() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("X", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 &quot; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property x1() As String
            Get
                Return ResourceManager.GetString("x1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
