'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.18010
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KillAds.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 127.0.0.1 localhost 
        '''127.0.0.1 mcfg.sandai.net 
        '''#173.213.83.82 mcfg.sandai.net 
        '''127.0.0.1 pubstat.sandai.net 
        '''127.0.0.1 wy.xunlei.com 
        '''127.0.0.1 buy.safe.xunlei.com 
        '''127.0.0.1 wa.kuwo.cn 
        '''173.213.83.82 dsc.taobaocdn.com 
        '''127.0.0.1 biz5.sandai.net 
        '''127.0.0.1 cknum.sandai.net 
        '''127.0.0.1 cl.kankan.xunlei.com 
        '''127.0.0.1 float.sandai.net 
        '''127.0.0.1 mcfg.sandai.net 
        '''#173.213.83.82 cl.kankan.xunlei.com 
        '''127.0.0.1 mtips.xunlei.com 
        '''127.0.0.1 211.94.190.80 
        '''127.0.0.1 advstat.xunlei.com 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property host() As String
            Get
                Return ResourceManager.GetString("host", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
